version: '3.7'
services:
  f-budget-api:
    image: docker.okidoo.co/node-dev-18:latest
    container_name: f-budget-api
    dns: 1.1.1.1
    env_file:
      - ./.f-budget-api.env
      - ./.git.env
    command: tail -F anything
    networks:
      - f-budget
      - yest-api
    ports:
      - ${API_PORT}:3000
    volumes:
      - ./.npmrc:/home/node/.npmrc
      - ../:/home/node/app
      - ~/.ssh/:/home/node/.ssh/
    environment:
      TZ: "America/Toronto"
    depends_on:
      f-budget-mongo:
        condition: service_healthy

  f-budget-mongo:
    image: mongo:latest
    ports:
      - ${MONGO_PORT_1}:27017
    env_file:
      - ./.mongo.env
    volumes:
      - ./mongo:/data/db
    networks:
      - f-budget
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017 --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  f-budget-minio:
    image: minio/minio:latest
    ports:
      - ${MINIO_9000}:9000
      - ${MINIO_9001}:9001
    env_file:
      - ./.minio.env
    networks:
      - f-budget
    volumes:
      - ./minio:/data
    command: server /data --console-address ":9001"

networks:
  f-budget:
  yest-api:
    external: true
    name: yest-api_yest-api
