openapi: 3.0.3
servers:
  - url: https://yest-stats-api.zone51.fun
info:
  description: This is a documentation for yest-stats-api
  x-locale: fr_CA
  version: 0.0.1
  title: api
  termsOfService: http://swagger.io/terms/
  contact:
    email: support@okidoo.ca
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
paths: {}
components:
  securitySchemes:
    admin:
      type: http
      scheme: bearer
      bearerFormat: JWT
    member:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Dummy:
      type: object
      properties:
        contract:
          $ref: "../../node_modules/@yest/contract/resources.yaml#/components/schemas/ResultHandlerInterface"
        healthcheck:
          $ref: "../../node_modules/@yest/healthcheck/resources.yaml#/components/schemas/Healthcheck"
        mongoose:
          $ref: "../../node_modules/@yest/mongoose/resources.yaml#/components/schemas/AccessModelCreate"
        # security:
        #   $ref: "../../node_modules/@yest/security/resources.yaml#/components/schemas/RefreshResponse"
    SupportedLanguage:
      type: string
      enum:
        - Fr
        - En